name: odelle_nyse
description: Odelle Nyse (ON) - Self-Actualization Operating System
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  just_audio: ^0.10.5
  flutter_tts: ^4.2.3
  googleapis: ^15.0.0
  url_launcher: ^6.3.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  google_sign_in: ^6.2.2
  flutter_webrtc: ^1.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  package_info_plus: ^9.0.0
  http: ^1.6.0
  flutter_facebook_auth: ^6.2.0
  font_awesome_flutter: ^10.7.0
  image: ^4.5.4
  flutter_svg: ^2.0.10+1
  web_socket_channel: ^3.0.3
  rive: ^0.13.4
  mic_stream: ^0.7.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "app-icon-black-large.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#000000"

flutter:
  uses-material-design: true
  assets:
    - .env
    - fonts/
    - assets/icons/
    - assets/images/
    - assets/riv/
